USE essv2436_cinema_noyant;



CREATE TABLE sessions
(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
date DATE NOT NULL,
time_perma VARCHAR(255) NOT NULL,
time_seance VARCHAR(255) NOT NULL
)
ENGINE=INNODB;

CREATE TABLE subscribers
(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
last_name VARCHAR(255) NOT NULL,
first_name VARCHAR(255) 
)
ENGINE=INNODB;


CREATE TABLE volunteers
(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,    
email VARCHAR(255) NOT NULL UNIQUE,
last_name VARCHAR(255) NOT NULL,
first_name VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
jeton VARCHAR(255) NOT NULL,
isAdmin TINYINT DEFAULT 0

)
ENGINE=INNODB;


CREATE TABLE availabilities
(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,    
available VARCHAR(255) NOT NULL,
volunteerId SMALLINT UNSIGNED NOT NULL,
sessionId SMALLINT UNSIGNED NOT NULL,
CONSTRAINT fk_volunteerId_availa FOREIGN KEY (volunteerId) REFERENCES volunteers(id)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT fk_sessionId_availa FOREIGN KEY (sessionId) REFERENCES sessions(id)
ON DELETE CASCADE
ON UPDATE CASCADE
)
ENGINE=INNODB;


